### PR TITLE
adding __main__ as a variable

### PR DESCRIPTION
**Pull request by szabolcsdombi**
- fix `if` for main programs

```
print('__name__ is %r' % __name__)

if __name__ == '__main__':
    raise Exception('hello')
```

### CODE REVIEW

**Comment by skorokithakis** [comment]
Hmm, can you elaborate on what this fixes exactly?

**Comment by szabolcsdombi** [comment]
Running `python -m tbvaccine test_main.py` prints `__name__ is builtins` and quits without an exception.

It is useful when running a single unittest. ( [example](https://docs.python.org/3/library/unittest.html#basic-example) )

test_main.py:
```
print('__name__ is %r' % __name__)

if __name__ == '__main__':
    raise Exception('hello')
```

**Comment by skorokithakis** [comment]
Ah, I see, thanks. Hopefully it doesn't break anything else by overwriting `__name__` when it shouldn't.

**Comment by szabolcsdombi** [comment]
Not sure if it will override the `__name__` for further imports. those get a different `globals()` and `locals()`

**Comment by szabolcsdombi** [comment]
Tested import with a random module:

```
__name__ is 'K'             # print from K.py
__name__ is '__main__'      # print from test_main.py
```

**Comment by skorokithakis** [comment]
Sounds good, thanks!

**Pull request merged**
