### PR TITLE
Update setup.py to require colorama on Windows

### LINKED ISSUE #31: Add colorama as a required dependency on Windows
Colorama is commonly used on Windows to allow output of coloured terminal text. Otherwise, the raw escape codes are printed (and no color :( ).

### PR DESCRIPTION
**Pull request by minchinweb**
Closes #31

### CODE REVIEW

**Review by skorokithakis — CHANGES_REQUESTED** [review]
This is great, but the plural in "tests requires" bugs me a bit 😛 Could you change it to `TESTS_REQUIRE`?

**Comment by minchinweb** [comment]
I think I got it fixed!

**Comment by minchinweb** [comment]
now black likes it. We should be good to go!

**Comment by skorokithakis** [comment]
Sorry, I didn't get a notification email for this for some reason. Looks great, thanks!

**Pull request merged**
